<h1>Lecture 4</h1>

In [7]:
import pathlib 
import pandas as pd
from IPython.display import display

cwd = pathlib.Path.cwd()
# get the files in the data folder
data_folder = cwd / 'data'
for item in data_folder.glob('*.xlsx'):
    
    # display the data in the excel file
    data = pd.read_excel(item)
    print(data)

   Unnamed: 0  Well being  Productivity  Energy  Stress  Anxiety  Depression
0  2023-10-01         5.0           5.0     5.0     1.0      1.0         1.0
1  2023-10-02         3.0           3.0     3.0     3.0      3.0         3.0
2  2023-10-03         1.0           1.0     1.0     5.0      5.0         5.0
3  2023-10-04         4.0           3.0     5.0     2.0      1.0         3.0
4  2023-10-05         NaN           NaN     NaN     NaN      NaN         NaN
5  2023-10-06         NaN           NaN     NaN     NaN      NaN         NaN
6  2023-10-07         NaN           NaN     NaN     NaN      NaN         NaN
7  2023-10-08         NaN           NaN     NaN     NaN      NaN         NaN
8  2023-10-09         NaN           NaN     NaN     NaN      NaN         NaN
9  2023-10-10         NaN           NaN     NaN     NaN      NaN         NaN
10 2023-10-11         NaN           NaN     NaN     NaN      NaN         NaN
11 2023-10-12         NaN           NaN     NaN     NaN      NaN         NaN

<h3>Viktige uttrykk for å jobbe med pathlib</h3>

* cwd.exists()
* cwd.is_dir()
* cwd.is_file()
* cwd.is_absolute()
* cwd.as_uri()

for path in Path('..').glob('Lecture_[123]/*.py'):


[123] betyr at den vil skjekke alle filene som har enten 1,2 eller 3 i denne karakterposisjonen

Vi kan generere nye mapper med å bruke "path.mkdir()"

In [34]:
from pathlib import Path
import yaml

dir = Path('Training')
if not dir.exists():
    dir.mkdir()

test_cases = ["CIFAR"+str(num) for num in range(10,100,10)]
learningsrates = [10**(-i) for i in range(1,7)]


for tc in test_cases:
    path_t = dir / tc 
    if not path_t.exists():
        path_t.mkdir()  
    for lr in learningsrates:
        with open(path_t / f"lr_{lr}.txt","w") as jfile:
            yaml.dump({"learningrate":lr, "epochs": 100},jfile)


<h3>Renaming folders and files</h3>



In [41]:
from pathlib import Path
demo_dir = Path('demo')

for old_name in demo_dir.glob('*/*.txt'):
    new_name = old_name[:-4]
    old_name.rename(new_name+'.yml')


<h1>Matrix data</h1>

We can build a matrix using nested lists, or numpy arrays

In [107]:
import numpy as np

A = [[i+j for i in range(4)] for j in range(2,5)]
B = [[i+j for i in range(4)] for j in range(2,5)]

#print(A)

def add(A,B):
    C = A.copy() # using shallow copy wont allocate new memory for the nested lists
    C = A.deepcopy() # using deepcopy will allocate new memory for the nested lists
    print(id(C)==id(A))
    C = [[0 for i in range(len(A))] for j in range(len(A))]
    for i, row_c in enumerate(C):
        for j, value_c in enumerate(row_c):
            C[i][j] = A[i][j] + B[i][j]
    print(id(C)==id(A))
    return C
print(np.array(A))
print(np.array(B))
np.array(add(A,B))


[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


AttributeError: 'list' object has no attribute 'deepcopy'

<h1>Memory Address</h1>

When defining an object using a pointer to a specific address in memory like when doing

* A = B, where B = somelist
* then id(A) = id(B)

the "copy" command, creates a new object with a different memory address, however this does not work in cases of nested lists
in this case you should use the "deepcopy" from the .copy library:
* from copy import deepcopy

If you want to modify very large datasets: use deepcopy

If you only want to read data: use equality sign